#ifndef ULOG_CONFIG_H
#define ULOG_CONFIG_H


#define ULOG_BUILD_COLOR             1
#define ULOG_BUILD_PREFIX_SIZE       64
#define ULOG_BUILD_EXTRA_OUTPUTS     8
#define ULOG_BUILD_SOURCE_LOCATION   1
#define ULOG_BUILD_LEVEL_SHORT       0
#define ULOG_BUILD_TIME              1
#define ULOG_BUILD_TOPICS_MODE       ULOG_BUILD_TOPICS_MODE_STATIC
#define ULOG_BUILD_TOPICS_STATIC_NUM 10
#define ULOG_BUILD_DYNAMIC_CONFIG    1
#define ULOG_BUILD_WARN_NOT_ENABLED  1
#endif /* ULOG_CONFIG_H */
